const userData = {
  githubUsername: 'sagitarisandy',
  name: 'Arya Sagitarisandy',
  fullname: 'Arya Fadhil Sagitarisandy',
  title: 'Building a successful product is a challenge. I am highly energetic in user experience design and interfaces',
  status: 'Fullstack Developer @SolarKita',
  country: '🇮🇩 Indonesia',
  desc: 'I am a full-stack developer with strong expertise in building and deploying scalable web and mobile applications. I specialize in React, Next.js, NestJS, Go Gin and Flutter, with hands-on experience in designing system architecture, databases, and reusable component libraries. My skills extend into DevOps, including deployment automation, CI/CD pipelines, containerization with Docker and Kubernetes, as well as cloud server management. I bring a holistic approach to creating secure, efficient, and user-centered digital products, from development to production deployment.',
  navLink: [
    { href: '/', label: 'Arya' },
    { href: '/about', label: 'About' },
    { href: '/work', label: 'Work' },
    // { href: '/articles', label: 'Articles' },
    { href: '/achievement', label: 'What People Say' },
    { href: '/link', label: 'Get in touch' },
  ],
  project: [
    {
      id: 1,
      nama: 'UMB (Mercu Buana University)',
      img: '/img/project/UMB.png',
      // img2: '/img/project/thumbnail-siakad.jpg',
      // type: 'Closed Source Project',
      desc: 'In this project I created a user interface for the academic system in lectures. I created several roles such as: study program/PRODI, lecturer, monitor, admin, and student. In this project I communicated and collaborated with the project manager/product manager and users.',
      stack: 'UI UX',
      country: '🇮🇩 Indonesia',
      url: 'https://www.mercubuana.ac.id/',
    },
    {
      id: 2,
      nama: 'Sylaps',
      img: '/img/project/Sylaps.png',
      // type: 'Closed Source Project',
      desc: 'Sylaps is available on every major browser (Google Chrome, Firefox, Opera) and native applications for Desktop and Mobile platforms. We`re making real-time, secure communication a reality by providing easy to use secure and reliable video conferencing solutions for everybody.',
      stack: 'Illustrator',
      country: '🇫🇷 France',
      url: 'https://sylaps.com/',
    },
    {
      id: 6,
      nama: 'SolarKita',
      img: '/img/project/SolarKita.png',
      // type: 'Closed Source Project',
      desc: 'SolarKita is a company based in Indonesia, here I am as a UI/UX Designer & Junior Mobile Developer with Flutter technology. This company serves the installation and sale of solar panels, not only that, they also have an application for sales and also customers to track solar panels.',
      stack: 'UI/UX ,Mobile Dev, Illustrator',  
      country: '🇮🇩 Indonesia',
      url: 'https://www.solarkita.com/',
    },
    {
      id: 14,
      nama: 'Alagille Syndrome Alliance',
      img: '/img/project/ALGSA.png',
      // type: 'Closed Source Project',
      desc: 'This project is a community and alliance platform dedicated to Alagille Syndrome. It includes features such as donations/fundraising, a blog, educational information, events, and research paper publications. Currently, the platform is in the development stage of a mobile application to enhance accessibility and community engagement.',
      stack: 'Mobile Developer, UI UX, Product Designer',  
      country: '🇺🇸 United States',
      url: 'https://alagille.org/',
    },
    {
      id: 4,
      nama: 'Soluty Renting',
      img: '/img/project/SolutyRenting.png',
      // type: 'Closed Source Project',
      desc: 'Soluty Renting is a service for renting vehicles, any vehicle ranging from motorbikes, vans, family cars, electric cars, and others. based in Germany.',
      stack: 'Illustrator',  
      country: '🇪🇸 Spain',
      url: 'https://solutyrenting.com/',
    },
    {
      id: 5,
      nama: 'Gurulabs',
      img: '/img/project/GuruLabs.png',
      // type: 'Closed Source Project',
      desc: 'Gurulabs is a multinational company based in America, as a UI/UX and illustrator I have to adjust the interface to suit users from various countries. Gurulabs provides digital marketing services, such as: Leads generation, SEO, Social Media Marketing, and others.',
      stack: 'Web Designer ,Illustrator',  
      country: '🇺🇸 United States',
      url: 'https://www.gurulabs.dev/',
    },
    {
      id: 13,
      nama: 'Pixel Dojo',
      img: '/img/project/pixeldojo.png',
      // type: 'Closed Source Project',
      desc: 'Design solutions for website, animation, and advertising.',
      stack: 'Illustrator',  
      country: '🇬🇧 United Kingdom',
      url: 'https://www.pixeldojo.co.uk/',
    },
    {
      id: 10,
      nama: 'Hotel Core',
      img: '/img/project/HotelCore.png',
      // type: 'Closed Source Project',
      desc: 'Web services for hotel',
      stack: 'Illustrator',  
      country: '🇩🇪 Germany',
      url: 'https://hotelcore.io/',
    },
    {
      id: 3,
      nama: 'CRM Guru',
      img: '/img/project/CrmGuru.png',
      // type: 'Closed Source Project',
      desc: 'This project is to create a web app for services to find experts in the field of CRM applications, and also for user assessment or user feedback for each CRM application.',
      stack: 'UI UX, Product Manager',  
      country: '🇺🇸 United States',
      url: '',
    },
    {
      id: 7,
      nama: 'Vasanta Estate Management',
      img: '/img/project/Vasanta.png',
      // type: 'Closed Source Project',
      desc: 'Vasanta Estate Management is an application service for people who own houses in the Shila at Sawangan housing complex, and also other projects by Vasanta .Tbk. Users can make monthly payments, book facilities, access in and out, make complaints, and more.',
      stack: 'UI/UX',  
      country: '🇮🇩 Indonesia',
      url: '',
    },
    {
      id: 8,
      nama: 'Group Greet',
      img: '/img/project/GroupGreet.png',
      // type: 'Closed Source Project',
      desc: 'Group Greet is a service for creating digital greeting cards. Example: you have a work friend who has a birthday, Group Greet creates an automatic system for sending cards via email, even if you send them a long time ago. and also with many greeting card variants.',
      stack: 'UI/UX, Illustrator, Web Designer',  
      country: '🇺🇸 United States',
      url: '',
    },
    {
      id: 9,
      nama: 'SQM/FAST',
      img: '/img/project/FAST.png',
      // type: 'Closed Source Project',
      desc: 'CRM web and mobile app for leads management.',
      stack: 'UI/UX, Illustrator, Web Designer',  
      country: '🇮🇩 Indonesia',
      url: 'https://preview.sqmproperty.co.id/',
    },{
      id: 11,
      nama: 'ThriveWorks',
      img: '/img/project/thriveworks.jpg',
      // type: 'Closed Source Project',
      desc: 'Thriveworks is an application designed to help manage household needs. It allows homeowners to book facilities, pay monthly bills, access the gate system, redeem vouchers, submit emergency requests, and many other features that enhance residents’ convenience and living experience.',
      stack: 'UI/UX',  
      country: '🇮🇩 Indonesia',
      url: '',
    },
    {
      id: 11,
      nama: 'Santa Forest',
      img: '/img/project/santaforest.png',
      // type: 'Closed Source Project',
      desc: 'Company selling Christmas trees.',
      stack: 'Illustrator',  
      country: '🇳🇿 New Zealand',
      url: 'https://www.santasforest.co.nz/',
    },
    {
      id: 12,
      nama: 'Mindset Dev',
      img: '/img/project/mindsetdev.png',
      // type: 'Closed Source Project',
      desc: 'MindsetDev is the world’s leading personal development community for achievers dedicated to helping you improve all aspects of your life through the power of mindset and self mastery.',
      stack: 'Illustrator',  
      country: '🇯🇵 Japan',
      url: 'https://mindsetdev.com/',
    },
  ],
  timeline: [
    {
      id: 1,
      title: 'SolarKita | 🇮🇩 Indonesia',
      year: 'Jan 2025 - Now',
      desc: '<ul style="list-style:none; padding:0; margin:0;"><li style="margin-bottom:12px;"><span>⚪ Develop the landing page, web-based & app-based leads management system, customer application, and solar panel monitoring system.</span></li><li style="margin-bottom:12px;"><span>⚪ Established a reusable design system & component library to ensure consistency across web and mobile platforms.</span></li><li style="margin-bottom:12px;"><span>⚪ Developed full-stack applications using React, Next.js, and NestJS.</span></li><li style="margin-bottom:12px;"><span>⚪ Built mobile applications using Flutter with Provider state management, implementing security measures for both Android and iOS platforms.</span></li><li style="margin-bottom:12px;"><span>⚪ Performed deployment/upload to servers, with hands-on experience in Linux CLI, Docker, and Kubernetes.</span></li><li style="margin-bottom:12px;"><span>⚪ Developed databases and created Entity Relationship Diagrams (ERD) to support system architecture.</span></li><li style="margin-bottom:12px;"><span>⚪ Gained knowledge of IoT systems by integrating inverter data collection and displaying it within the customer app.</span></li><li style="margin-bottom:12px;"><span>⚪ Familiar with App Store Connect and Google Play Console for mobile app publishing and management.</span></li></ul>',
    },
  //   {
  //     id: 2,
  //     title: 'Elevate Designs | 🇺🇸 United States',
  //     year: 'Des 2024 - Now',
  // desc: '<ul style="list-style:none; padding:0; margin:0;"><li style="margin-bottom:12px;"><span>⚪ Worked on UI/UX design for websites across various U.S. regions, including Florida, Michigan, Los Angeles, and more.</span></li><li style="margin-bottom:12px;"><span>⚪ Handled projects with diverse client segments, ranging from dental clinics, vehicle storage facilities, roofing services, pool renovation, community organizations, crowdfunding platforms, and others.</span></li><li style="margin-bottom:12px;"><span>⚪ Collaborated with international teams across different regions to exchange ideas and execute design concepts effectively.</span></li><li style="margin-bottom:12px;"><span>⚪ Created graphic design assets such as brochures, banners, flyers, logos, and other marketing materials.</span></li><li style="margin-bottom:12px;"><span>⚪ Create image manipulation/editing using Photoshop, and illustrations using Illustrator.</span></li></ul>',
  //   },
    {
      id: 3,
      title: 'SQM Property | 🇮🇩 Indonesia',
      year: 'Aug 2022 - Des 2024',
  desc: '<ul style="list-style:none; padding:0; margin:0;"><li style="margin-bottom:12px;"><span>⚪ Create CRM design including workflow for Web App & Mobile App.</span></li><li style="margin-bottom:12px;"><span>⚪ Listen to stakeholders and user needs, then discuss with the team.</span></li><li style="margin-bottom:12px;"><span>⚪ Recreate website and mobile displays with flow and UI that is easy for users to understand.</span></li><li style="margin-bottom:12px;"><span>⚪ Create side project by VASANTA.Tbk for Estate Management Web App & Mobile App.</span></li>',
    },
  //   {
  //     id: 4,
  //     title: 'Soluty Renting | 🇪🇸 Spain',
  //     year: 'Jan 2022 - Mei 2022',
  // desc: '<ul style="list-style:none; padding:0; margin:0;"><li style="margin-bottom:12px;"><span>⚪ User Interface research comparing the German car rental market.</span></li><li style="margin-bottom:12px;"><span>⚪ Direct communication with the CEO and CTO and listening to their needs.</span></li><li style="margin-bottom:12px;"><span>⚪ Creating illustration assets for the website.</span></li></ul>',
  //   },
  //   {
  //     id: 5,
  //     title: 'Sylaps | 🇫🇷 France',
  //     year: 'Apr 2021 - Okt 2021',
  // desc: '<ul style="list-style:none; padding:0; margin:0;"><li style="margin-bottom:12px;"><span>⚪ Communication and understanding market needs by considering competitors using qualitative research methods, in-depth interviews, and competitor analysis.</span></li><li style="margin-bottom:12px;"><span>⚪ Implementation of user interfaces according to research methods.</span></li><li style="margin-bottom:12px;"><span>⚪ Communication with Product Owners, listening to what they need.</span></li><li style="margin-bottom:12px;"><span>⚪ Creation of illustration & icon assets.</span></li></ul>',
  //   },
  //   {
  //     id: 6,
  //     title: 'Gurulabs | 🇺🇸 United States',
  //     year: 'Nov 2020 - Feb  2021',
  // desc: '<ul style="list-style:none; padding:0; margin:0;"><li style="margin-bottom:12px;"><span>⚪ Web service creation for digital marketing agencies.</span></li><li style="margin-bottom:12px;"><span>⚪ Landing page creation by conducting research from competitors in the same field.</span></li><li style="margin-bottom:12px;"><span>⚪ Implementation of strategies on landing pages that influence readers to be interested in the services.</span></li><li style="margin-bottom:12px;"><span>⚪ Detailed asset creation, layout, and research for UX writing.</span></li></ul>',
  //   },
  ],
  social: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/sagitarisandy',
      icon: '/img/icon/github.svg',
    },
    {
      id: 2,
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/arya-fadhil-sagitarisandy-b140831a8/',
      icon: '/img/icon/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/sagitarisandy/',
      icon: '/img/icon/instagram.svg',
    },
    // {
    //   id: 4,
    //   name: 'Facebook',
    //   link: 'https://www.facebook.com/ryandinulfatah',
    //   icon: '/img/icon/facebook.svg',
    // },
    {
      id: 4,
      name: 'Medium',
      link: 'https://medium.com/@sagitarisandybusiness',
      icon: '/img/icon/book-open.svg',
    },
    {
      id: 5,
      name: 'Email',
      link: 'mailto:sagitarisandybusiness@gmail.com',
      icon: '/img/icon/mail.svg',
    },
  ],
  techStack: [
    {
      id: 7,
      name: 'React Native',
      type: 'containerized',
      icon: '/img/icon/react.svg',
      year: '6 month',
    },
    {
      id: 9,
      name: 'Flutter',
      type: 'containerized',
      icon: '/img/icon/flutter.svg',
      year: '1 year',
    },
    {
      id: 10,
      name: 'Dart',
      type: 'containerized',
      icon: '/img/icon/dart.png',
      year: '1 year',
    },
    {
      id: 10,
      name: 'Xcode',
      type: 'containerized',
      icon: '/img/icon/xcode.png',
      year: '1 year',
    },
    {
      id: 10,
      name: 'App Store Connect',
      type: 'containerized',
      icon: '/img/icon/app-store-connect.webp',
      year: '1 year',
    },
    {
      id: 10,
      name: 'Google Play Console',
      type: 'containerized',
      icon: '/img/icon/google-play-console.png',
      year: '1 year',
    },
    {
      id: 8,
      name: 'React',
      type: 'containerized',
      icon: '/img/icon/react.svg',
      year: '1 year',
    },
    {
      id: 11,
      name: 'Javascript',
      type: 'containerized',
      icon: '/img/icon/javascript.svg',
      year: '2 year',
    },
    {
      id: 8,
      name: 'Typescript',
      type: 'containerized',
      icon: '/img/icon/typescript.png',
      year: '1 year',
    },
    {
      id: 8,
      name: 'Nest JS',
      type: 'containerized',
      icon: '/img/icon/nest-js.svg',
      year: '3 month',
    },
    {
      id: 8,
      name: 'Gin',
      type: 'containerized',
      icon: '/img/icon/gin.png',
      year: '1 month',
    },
    {
      id: 8,
      name: 'Go',
      type: 'containerized',
      icon: '/img/icon/go.png',
      year: '1 month',
    },
    {
      id: 8,
      name: 'My SQL',
      type: 'containerized',
      icon: '/img/icon/my-sql.png',
      year: '1 year',
    },
    {
      id: 8,
      name: 'Docker',
      type: 'containerized',
      icon: '/img/icon/docker.png',
      year: '1 year',
    },
    {
      id: 8,
      name: 'Kubernetes',
      type: 'containerized',
      icon: '/img/icon/kubernetes.png',
      year: '1 year',
    },
    // {
    //   id: 1,
    //   name: 'illustrator',
    //   type: 'database',
    //   icon: '/img/icon/adobe-illustrator.svg',
    //   year: '7 years',
    // },
    // {
    //   id: 2,
    //   name: 'Photoshop',
    //   type: 'programming',
    //   icon: '/img/icon/Adobe-Photoshop.svg',
    //   year: '7 year',
    // },
    // {
    //   id: 3,
    //   name: 'Adobe After Effects',
    //   type: 'programming',
    //   icon: '/img/icon/Adobe-After.svg',
    //   year: '2 year',
    // },
    // {
    //   id: 4,
    //   name: 'Figma',
    //   type: 'programming',
    //   icon: '/img/icon/Figma-logo.svg',
    //   year: '5 year',
    // },
    // {
    //   id: 5,
    //   name: 'Procreate',
    //   type: 'containerized',
    //   icon: '/img/icon/Procreate.svg',
    //   year: '6 year',
    // },
    // {
    //   id: 6,
    //   name: 'Maze',
    //   type: 'containerized',
    //   icon: '/img/icon/maze.jpeg',
    //   year: '1 year',
    // },
    // {
    //   id: 12,
    //   name: 'CSS',
    //   type: 'containerized',
    //   icon: '/img/icon/css3.svg',
    //   year: '2 year',
    // },
    // {
    //   id: 13,
    //   name: 'HTML',
    //   type: 'containerized',
    //   icon: '/img/icon/html5.svg',
    //   year: '2 year',
    // }
  ],
  testimonials: [
    
    {
      id: 1,
      name: 'Camping Store Panama',
      desc: 'It was wonderful working with Arya. He was very patient, talented, and very responsive. He quickly got the idea of what we needed. He chose a colour palette that goes perfect with our branding. The artwork turned out more awesome than  expected!  Im sure I will work with Arya again.',
      profile: '/img/certificate/camping-store.jpg',
      country: '🇵🇦 Panama',
    },
    {
      id: 2,
      name: 'Soluty Renting',
      desc: 'Really great work! The communication was easy, he totally understood our needs and gave us a excellent work. Hope we collaborate further',
      profile: '/Logo/soluty-renting-logo.png',
      country: '🇪🇸 Spain',
    },
    {
      id: 3,
      name: 'Dianna - Group Greet',
      desc: 'Sagitarisandy was excellent in asking questions upfront about the direction and the motivation behind my ask. I got a sketch to confirm the outline and updates throughout. He was prompt, took my feedback well and executed it, and delivered an excellent piece! I know where to go in the future for awesome digital illustrations!',
      profile: '/img/certificate/kristen-stewart.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 4,
      name: 'Tdao - Simplex Source',
      desc: 'Its always a pleasure working w Arya. He understood our requirements and delivered exactly our vision. He even fix his previous designs for us so they can match with the new ones.',
      profile: '/img/certificate/tdao.webp',
      country: '🇻🇳 Vietnam',
    },
    // {
    //   id: 5,
    //   name: 'Mike',
    //   desc: 'Always a pleasure working Arya! Love his work.',
    //   profile: '/img/certificate/mike.webp',
    //   country: '🇺🇸 United States',
    // },
    {
      id: 6,
      name: 'Ejfran',
      desc: 'It was fantastic sagitarisandy made sure that my request fit my needs. We look over where the image would be used and he was able to work out my ideas and produced the best image for the project. sagitarisandy is very creative and responsive to input.',
      profile: '/img/certificate/mike.webp',
      country: '🇺🇸 United States',
    },
    // {
    //   id: 7,
    //   name: 'Notion Gems',
    //   desc: 'I aimed to present a polished image on my Twitter profile, and his illustration work was just what I needed. The avatar and cover were superb in quality, and I am delighted with the outcome. Strongly recommend.',
    //   profile: '/img/certificate/mike.webp',
    //   country: '🇮🇹 Italy',
    // },
    {
      id: 8,
      name: 'Joanna',
      desc: 'Super travail comme dhabitude ! Bravo Arya et merci !',
      profile: '/img/certificate/joanna.jpg',
      country: '🇫🇷 France',
    },
    {
      id: 9,
      name: 'Hasan - Pixel Dojo',
      desc: 'Great work! Arya is a very talented illustrator and I’ll definitely hire for my future projects. Highly recommend',
      profile: '/img/certificate/hasan.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 10,
      name: 'Himanshu Batra - Gurulabs & CRM Guru',
      desc: 'Hes gold on this field. You shouldnt look further if youre looking for an illustration or website design. I had fun working with him on our website. He has built a full website confidently, and small changes went smoothly, and he had no issue with tiny changes or re-work. If youre looking for UI design, Figma Web Sites & Illustration for your website, he should be your go-to guy. Dont look any further. I highly recommend him for any web design-related projects. Must use.',
      profile: '/img/certificate/asharib-naseer.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 11,
      name: 'Jacob - Santa Forest',
      desc: 'His work is amazing and beyond my expectations. I would recommend him to everyone. He did many revisions with speed and no complaints. Hes the man! He also gave my advice on the design of my website, which is excellent.',
      profile: '/img/certificate/jacob.webp',
      country: '🇳🇿 New Zealand',
    },
  ],
  link: [
    {
      id: 1,
      text: 'View My Resume',
      url: 'https://drive.google.com/file/d/13E1ZK_oTGrosbZsIbLvAKgFCcKumaTaT/view?usp=sharing',
    },
    {
      id: 2,
      text: 'Project Portofolio | download to preview',
      url: 'https://drive.google.com/file/d/1GKU1E2el9ctfq71_jtArMr_A09bsRlt2/view?usp=drive_link',
    },
    {
      id: 3,
      text: 'My Dribbble',
      url: 'https://dribbble.com/sagitarisandy/shots',
    },
    {
      id: 4,
      text: 'My Instagram',
      url: 'https://www.instagram.com/sagitarisandy/',
    },
    {
      id: 5,
      text: 'Send me an email',
      url: 'mailto:sagitarisandybusiness@gmail.com',
    },
    {
      id: 6,
      text: 'My Linkedin',
      url: 'https://www.linkedin.com/in/arya-fadhil-sagitarisandy-b140831a8/',
    },
    {
      id: 7,
      text: 'My Github',
      url: 'https://github.com/sagitarisandy',
    }
  ],
  sertifikasi: [
    {
      id: 1,
      title: 'Job : Frontend-Development Admin Design',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-2.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 2,
      title: 'Job : Need Laravel & MySQL for Develop App',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-1.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 3,
      title: 'Belajar Dasar Pemrograman Web',
      platform: 'Dicoding',
      img: '/img/certificate/new-dasar-web.png',
      url: 'https://www.dicoding.com/certificates/L4PQ3E06VPO1',
    },
    {
      id: 4,
      title: 'Belajar Fundamental Front-end Web Development',
      platform: 'Dicoding',
      img: '/img/certificate/new-frontend-fundamental.png',
      url: 'https://www.dicoding.com/certificates/MEPJLQ1KWZ3V',
    },
    {
      id: 5,
      title: 'Belajar Prinsip Pemrograman SOLID',
      platform: 'Dicoding',
      img: '/img/certificate/new-solid.png',
      url: 'https://www.dicoding.com/certificates/72ZDE5L99PYW',
    },
    {
      id: 6,
      title: 'Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)',
      platform: 'Dicoding',
      img: '/img/certificate/new-aws-dasar.png',
      url: 'https://www.dicoding.com/certificates/ERZR4E6MQZYV',
    },
    {
      id: 7,
      title: 'Basic English Online Course for Programmer',
      platform: 'YEC.CO.ID',
      img: '/img/certificate/new-eng.png',
      url: '#',
    },
    {
      id: 8,
      title: 'Baparekraf Developer Day 2020',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-dev-day-2020.png',
      url: '#',
    },
    {
      id: 9,
      title: 'IDCAMP Virtual Graduation 2019',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-virtual-graduation-2019.png',
      url: '#',
    },
    {
      id: 10,
      title: 'Course Studi Kasus Web Geolocation Laravel & Here Maps API',
      platform: 'Codepolitan',
      img: '/img/certificate/new-codepol.png',
      url: '#',
    },
    {
      id: 11,
      title: 'The Fundamentals of Digital Marketing',
      platform: 'Google Digital Garage',
      img: '/img/certificate/new-google-digital-marketing.png',
      url: '#',
    },
  ],
}
export default userData
