const userData = {
  githubUsername: 'Ryandinulfatah12',
  name: 'Arya Sagitarisandy',
  fullname: 'Arya Fadhil Sagitarisandy',
  title: 'Building a successful product is a challenge. I am highly energetic in user experience design and interfaces. Also I am currently studying web and app development',
  status: '#UI/X & Graphic Designer @SQMProperty',
  country: '🇮🇩 Indonesia',
  desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  navLink: [
    { href: '/', label: 'Arya' },
    { href: '/about', label: 'About' },
    { href: '/work', label: 'Work' },
    // { href: '/articles', label: 'Articles' },
    { href: '/achievement', label: 'Testimonials' },
    { href: '/link', label: 'Get in touch' },
  ],
  project: [
    {
      id: 1,
      nama: 'Thriveworks Estate Management',
      img: '/img/project/thriveworks.jpg',
      img2: '/img/project/thumbnail-siakad.jpg',
      type: 'Closed Source Project',
      desc: 'Website ini menyajikan informasi tentang berbagai lembaga pendidikan yang dikelola Pondok Pesantren KHAS, baik formal maupun nonformal. Untuk informasi lebih lanjut, silakan kunjungi website KHAS Al-Jaelani.',
      desc2: 'Website ini menyajikan informasi tentang berbagai lembaga pendidikan yang dikelola Pondok Pesantren KHAS, baik formal maupun nonformal. Untuk informasi lebih lanjut, silakan kunjungi website KHAS Al-Jaelani.',
      stack: 'UI UX',
      country: '🇮🇩 Indonesia',
      url: 'https://stieskhas.ac.id/',
    },
    {
      id: 1,
      nama: 'Academic and Information System Project',
      img: '/img/project/thumbnail-siakad.jpg',
      type: 'Closed Source Project',
      desc: 'Website ini menyajikan informasi tentang berbagai lembaga pendidikan yang dikelola Pondok Pesantren KHAS, baik formal maupun nonformal. Untuk informasi lebih lanjut, silakan kunjungi website KHAS Al-Jaelani.',
      stack: 'Illustration',
      country: '🇯🇵 Japan',
      url: 'https://stieskhas.ac.id/',
    },
  ],
  timeline: [
    {
      id: 1,
      title: 'UI/X and Graphic Designer at SQM Property',
      year: '2022 - now',
      desc: '<ul> <li><span>⚪ Listen to client and user needs, then discuss with the team.</span></li><li><span>⚪ Research from various real applications and also the habits of various people.</span></li><li><span>⚪ Recreate website and mobile displays with flow and UI that is easy for users to understand</span></li><li><span>⚪ Collaboration with the Front-End team on whether the UI will work effectively or not.</span></li><li><span>⚪ Create image manipulation/editing using Photoshop, and illustrations using Illustrator.</span></li></ul>',
    },
    {
      id: 2,
      title: 'Freelance illustrator, UI/X designer, and graphic designer',
      year: '2016 - 2022',
      desc: '<ul> <li><span>⚪ Helping various startups in a total of 22+ countries in the field of UI/X and graphic designers</span></li> <li><span>⚪ Communicate using English and understanding business models.</span></li><li><span>⚪ Adjust the style according to the clients request or fulfill the clients wishes</span></li></ul>',
    }
  ],
  social: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/Ryandinulfatah12',
      icon: '/img/icon/github.svg',
    },
    {
      id: 2,
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/ryandinulfatah/',
      icon: '/img/icon/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/ryandinulfatah12/',
      icon: '/img/icon/instagram.svg',
    },
    {
      id: 4,
      name: 'Facebook',
      link: 'https://www.facebook.com/ryandinulfatah',
      icon: '/img/icon/facebook.svg',
    },
    {
      id: 5,
      name: 'Medium',
      link: 'https://medium.com/@ryandinulfatah',
      icon: '/img/icon/book-open.svg',
    },
    {
      id: 6,
      name: 'Email',
      link: 'mailto:dinulfatahryan@gmail.com',
      icon: '/img/icon/mail.svg',
    },
  ],
  techStack: [
    {
      id: 5,
      name: 'illustrator',
      type: 'database',
      icon: '/img/icon/adobe-illustrator.svg',
      year: '5 years',
    },
    {
      id: 6,
      name: 'Photoshop',
      type: 'programming',
      icon: '/img/icon/Adobe-Photoshop.svg',
      year: '6 year',
    },
    {
      id: 11,
      name: 'Adobe After Effects',
      type: 'programming',
      icon: '/img/icon/Adobe-After.svg',
      year: '1 year',
    },
    {
      id: 11,
      name: 'Figma',
      type: 'programming',
      icon: '/img/icon/Figma-logo.svg',
      year: '4 year',
    },
    {
      id: 15,
      name: 'Procreate',
      type: 'containerized',
      icon: '/img/icon/Procreate.svg',
      year: '4 year',
    }
  ],
  testimonials: [
    {
      id: 1,
      name: 'Himanshu Batra',
      desc: 'Hes gold on this field. You shouldnt look further if youre looking for an illustration or website design. I had fun working with him on our website. He has built a full website confidently, and small changes went smoothly, and he had no issue with tiny changes or re-work. If youre looking for UI design, Figma Web Sites & Illustration for your website, he should be your go-to guy. Dont look any further. I highly recommend him for any web design-related projects. Must use.',
      profile: '/img/certificate/asharib-naseer.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 2,
      name: 'Jacob',
      desc: 'His work is amazing and beyond my expectations. I would recommend him to everyone. He did many revisions with speed and no complaints. Hes the man! He also gave my advice on the design of my website, which is excellent.',
      profile: '/img/certificate/jacob.webp',
      country: '🇳🇿 New Zealand',
    },
    {
      id: 3,
      name: 'Dianna',
      desc: 'Sagitarisandy was excellent in asking questions upfront about the direction and the motivation behind my ask. I got a sketch to confirm the outline and updates throughout. He was prompt, took my feedback well and executed it, and delivered an excellent piece! I know where to go in the future for awesome digital illustrations!',
      profile: '/img/certificate/kristen-stewart.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 4,
      name: 'Tdao',
      desc: 'Its always a pleasure working w Arya. He understood our requirements and delivered exactly our vision. He even fix his previous designs for us so they can match with the new ones.',
      profile: '/img/certificate/tdao.webp',
      country: '🇻🇳 Vietnam',
    },
    {
      id: 5,
      name: 'Mike',
      desc: 'Always a pleasure working Arya! Love his work.',
      profile: '/img/certificate/mike.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 6,
      name: 'Ejfran',
      desc: 'It was fantastic sagitarisandy made sure that my request fit my needs. We look over where the image would be used and he was able to work out my ideas and produced the best image for the project. sagitarisandy is very creative and responsive to input.',
      profile: '/img/certificate/mike.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 7,
      name: 'Notion Gems',
      desc: 'I aimed to present a polished image on my Twitter profile, and his illustration work was just what I needed. The avatar and cover were superb in quality, and I am delighted with the outcome. Strongly recommend.',
      profile: '/img/certificate/mike.webp',
      country: '🇮🇹 Italy',
    },
    {
      id: 8,
      name: 'Joanna',
      desc: 'Super travail comme dhabitude ! Bravo Arya et merci !',
      profile: '/img/certificate/joanna.jpg',
      country: '🇫🇷 France',
    },
    {
      id: 9,
      name: 'Hasan',
      desc: 'Great work! Arya is a very talented illustrator and I’ll definitely hire for my future projects. Highly recommend',
      profile: '/img/certificate/hasan.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 10,
      name: 'Camping Store Panama',
      desc: 'It was wonderful working with Arya. He was very patient, talented, and very responsive. He quickly got the idea of what we needed. He chose a colour palette that goes perfect with our branding. The artwork turned out more awesome than  expected!  Im sure I will work with Arya again.',
      profile: '/img/certificate/camping-store.jpg',
      country: '🇵🇦 Panama',
    }
  ],
  link: [
    {
      id: 1,
      text: 'View My Resume',
      url: 'https://drive.google.com/file/d/1PRi_nqHr526zvo3uaDZ3j5c-QjxVidOV/view?usp=sharing',
    },
    {
      id: 2,
      text: 'My Github',
      url: 'https://github.com/Ryandinulfatah12',
    },
    {
      id: 3,
      text: 'My Instagram',
      url: 'https://www.instagram.com/ryandinulfatah12/',
    },
    {
      id: 4,
      text: 'Send me an email',
      url: 'mailto:dinulfatahryan@gmail.com',
    },
    {
      id: 5,
      text: 'My Linkedin',
      url: 'https://www.linkedin.com/in/ryandinulfatah/',
    },
    {
      id: 6,
      text: 'My Facebook',
      url: 'https://www.facebook.com/ryandinulfatah',
    },
    {
      id: 7,
      text: 'My Medium',
      url: 'https://medium.com/@ryandinulfatah',
    }
  ],
  sertifikasi: [
    {
      id: 1,
      title: 'Job : Frontend-Development Admin Design',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-2.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 2,
      title: 'Job : Need Laravel & MySQL for Develop App',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-1.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 3,
      title: 'Belajar Dasar Pemrograman Web',
      platform: 'Dicoding',
      img: '/img/certificate/new-dasar-web.png',
      url: 'https://www.dicoding.com/certificates/L4PQ3E06VPO1',
    },
    {
      id: 4,
      title: 'Belajar Fundamental Front-end Web Development',
      platform: 'Dicoding',
      img: '/img/certificate/new-frontend-fundamental.png',
      url: 'https://www.dicoding.com/certificates/MEPJLQ1KWZ3V',
    },
    {
      id: 5,
      title: 'Belajar Prinsip Pemrograman SOLID',
      platform: 'Dicoding',
      img: '/img/certificate/new-solid.png',
      url: 'https://www.dicoding.com/certificates/72ZDE5L99PYW',
    },
    {
      id: 6,
      title: 'Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)',
      platform: 'Dicoding',
      img: '/img/certificate/new-aws-dasar.png',
      url: 'https://www.dicoding.com/certificates/ERZR4E6MQZYV',
    },
    {
      id: 7,
      title: 'Basic English Online Course for Programmer',
      platform: 'YEC.CO.ID',
      img: '/img/certificate/new-eng.png',
      url: '#',
    },
    {
      id: 8,
      title: 'Baparekraf Developer Day 2020',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-dev-day-2020.png',
      url: '#',
    },
    {
      id: 9,
      title: 'IDCAMP Virtual Graduation 2019',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-virtual-graduation-2019.png',
      url: '#',
    },
    {
      id: 10,
      title: 'Course Studi Kasus Web Geolocation Laravel & Here Maps API',
      platform: 'Codepolitan',
      img: '/img/certificate/new-codepol.png',
      url: '#',
    },
    {
      id: 11,
      title: 'The Fundamentals of Digital Marketing',
      platform: 'Google Digital Garage',
      img: '/img/certificate/new-google-digital-marketing.png',
      url: '#',
    },
  ],
}
export default userData
