const userData = {
  githubUsername: 'sagitarisandy',
  name: 'Arya Sagitarisandy',
  fullname: 'Arya Fadhil Sagitarisandy',
  title: 'Building a successful product is a challenge. I am highly energetic in user experience design and interfaces',
  status: '#UI/X & Graphic Designer @SQMProperty',
  country: '🇮🇩 Indonesia',
  desc: 'Thanks to my family background in printing and design. Growing up, I was always surrounded by creativity, and I started using tools like Photoshop and CorelDraw at a young age. With a bachelor`s degree in computer engineering, I am familiar with components in react, react native, and widgets in flutter. And another thing is I am easy to get along with someone even I have worked with more than 22+ countries, making me more active in finding User Experience and User Interface.',
  navLink: [
    { href: '/', label: 'Arya' },
    { href: '/about', label: 'About' },
    { href: '/work', label: 'Work' },
    // { href: '/articles', label: 'Articles' },
    // { href: '/achievement', label: 'What People Say' },
    { href: '/link', label: 'Get in touch' },
  ],
  project: [
    {
      id: 1,
      nama: 'UMB (Universitas Mercu Buana',
      img: '/img/project/UMB.png',
      // img2: '/img/project/thumbnail-siakad.jpg',
      // type: 'Closed Source Project',
      desc: 'In this project I created a user interface for the academic system in lectures. I created several roles such as: study program/PRODI, lecturer, monitor, admin, and student. In this project I communicated and collaborated with the project manager/product manager and users.',
      stack: 'UI UX',
      country: '🇮🇩 Indonesia',
      url: '',
    },
    {
      id: 2,
      nama: 'Sylaps',
      img: '/img/project/Sylaps.png',
      // type: 'Closed Source Project',
      desc: 'Sylaps is available on every major browser (Google Chrome, Firefox, Opera) and native applications for Desktop and Mobile platforms. We`re making real-time, secure communication a reality by providing easy to use secure and reliable video conferencing solutions for everybody.',
      stack: 'Illustrator',
      country: '🇫🇷 France',
      url: 'https://sylaps.com/',
    },
    {
      id: 3,
      nama: 'CRM Guru',
      img: '/img/project/CrmGuru.png',
      // type: 'Closed Source Project',
      desc: 'This project is to create a web app for services to find experts in the field of CRM applications, and also for user assessment or user feedback for each CRM application.',
      stack: 'UI UX, Product Manager',  
      country: '🇺🇸 United States',
      url: '',
    },
    {
      id: 4,
      nama: 'Soluty Renting',
      img: '/img/project/SolutyRenting.png',
      // type: 'Closed Source Project',
      desc: 'Soluty Renting is a service for renting vehicles, any vehicle ranging from motorbikes, vans, family cars, electric cars, and others. based in Germany.',
      stack: 'Illustrator',  
      country: '🇪🇸 Spain',
      url: 'https://solutyrenting.com/',
    },
    {
      id: 5,
      nama: 'Gurulabs',
      img: '/img/project/GuruLabs.png',
      // type: 'Closed Source Project',
      desc: 'Gurulabs is a multinational company based in America, as a UI/UX and illustrator I have to adjust the interface to suit users from various countries. Gurulabs provides digital marketing services, such as: Leads generation, SEO, Social Media Marketing, and others.',
      stack: 'Web Designer ,Illustrator',  
      country: '🇺🇸 United States',
      url: 'https://www.gurulabs.dev/',
    },
    {
      id: 6,
      nama: 'SolarKita',
      img: '/img/project/SolarKita.png',
      // type: 'Closed Source Project',
      desc: 'SolarKita is a company based in Indonesia, here I am as a UI/UX Designer & Junior Mobile Developer with Flutter technology. This company serves the installation and sale of solar panels, not only that, they also have an application for sales and also customers to track solar panels.',
      stack: 'UI/UX ,Illustrator',  
      country: '🇮🇩 Indonesia',
      url: 'https://www.solarkita.com/',
    },
    {
      id: 7,
      nama: 'Vasanta Estate Management',
      img: '/img/project/Vasanta.png',
      // type: 'Closed Source Project',
      desc: 'Vasanta Estate Management is an application service for people who own houses in the Shila at Sawangan housing complex, and also other projects by Vasanta .Tbk. Users can make monthly payments, book facilities, access in and out, make complaints, and more.',
      stack: 'UI/UX',  
      country: '🇮🇩 Indonesia',
      url: '',
    },
    {
      id: 8,
      nama: 'Group Greet',
      img: '/img/project/GroupGreet.png',
      // type: 'Closed Source Project',
      desc: 'Group Greet is a service for creating digital greeting cards. Example: you have a work friend who has a birthday, Group Greet creates an automatic system for sending cards via email, even if you send them a long time ago. and also with many greeting card variants.',
      stack: 'UI/UX, Illustrator, Web Designer',  
      country: '🇺🇸 United States',
      url: '',
    },
    {
      id: 9,
      nama: 'SQM/FAST',
      img: '/img/project/FAST.png',
      // type: 'Closed Source Project',
      desc: 'CRM web and mobile app for leads management.',
      stack: 'UI/UX, Illustrator, Web Designer',  
      country: '🇮🇩 Indonesia',
      url: 'https://preview.sqmproperty.co.id/',
    },
    {
      id: 10,
      nama: 'Hotel Core',
      img: '/img/project/HotelCore.png',
      // type: 'Closed Source Project',
      desc: 'Web services for hotel',
      stack: 'Illustrator',  
      country: '🇩🇪 Germany',
      url: 'https://hotelcore.io/',
    },
    {
      id: 11,
      nama: 'Santa Forest',
      img: '/img/project/santaforest.png',
      // type: 'Closed Source Project',
      desc: 'Company selling Christmas trees.',
      stack: 'Illustrator',  
      country: '🇳🇿 New Zealand',
      url: 'https://www.santasforest.co.nz/',
    },
    {
      id: 12,
      nama: 'Mindset Dev',
      img: '/img/project/mindsetdev.png',
      // type: 'Closed Source Project',
      desc: 'MindsetDev is the world’s leading personal development community for achievers dedicated to helping you improve all aspects of your life through the power of mindset and self mastery.',
      stack: 'Illustrator',  
      country: '🇯🇵 Japan',
      url: 'https://mindsetdev.com/',
    },
    {
      id: 13,
      nama: 'Pixel Dojo',
      img: '/img/project/pixeldojo.png',
      // type: 'Closed Source Project',
      desc: 'Design solutions for website, animation, and advertising.',
      stack: 'Illustrator',  
      country: '🇬🇧 United Kingdom',
      url: 'https://www.pixeldojo.co.uk/',
    },
  ],
  timeline: [
    {
      id: 1,
      title: 'UI/X and Graphic Designer at SQM Property',
      year: '2022 - now',
      desc: '<ul> <li><span>⚪ Listen to client and user needs, then discuss with the team.</span></li><li><span>⚪ Research from various real applications and also the habits of various people.</span></li><li><span>⚪ Recreate website and mobile displays with flow and UI that is easy for users to understand</span></li><li><span>⚪ Collaboration with the Front-End team on whether the UI will work effectively or not.</span></li><li><span>⚪ Create image manipulation/editing using Photoshop, and illustrations using Illustrator.</span></li></ul>',
    },
    {
      id: 2,
      title: 'Soluty Renting',
      year: 'Jan 2022 - Mei 2022',
      desc: '<ul> <li><span>⚪ User Interface research comparing the German car rental market.</span></li> <li><span>⚪ Direct communication with the CEO and CTO and listening to their needs.</span></li><li><span>⚪ Creating illustration assets for the website</span></li></ul>',
    },
    {
      id: 3,
      title: 'Sylaps',
      year: 'Apr 2021 - Okt 2021',
      desc: '<ul> <li><span>⚪ Communication and understanding market needs by considering competitors using qualitative research methods, in-depth interviews, and competitor analysis.</span></li> <li><span>⚪ Implementation of user interfaces according to research methods.</span></li><li><span>⚪ Communication with Product Owners, listening to what they need.</span></li></ul> ⚪ Creation of illustration & Icon  assets.</span></li></ul>',
    },
    {
      id: 4,
      title: 'Gurulabs',
      year: 'Nov 2020 - Feb  2021',
      desc: '<ul> <li><span>⚪ Web service creation for digital marketing agencies.</span></li> <li><span>⚪ Landing page creation, by conducting research from competitors in the same field.</span></li><li><span>⚪ Implementation of strategies on landing pages that influence readers to be interested in the services.</span></li></ul> ⚪ Detailed asset creation, layout, and research for UX writing.</span></li></ul>',
    },
  ],
  social: [
    {
      id: 1,
      name: 'Github',
      link: 'https://github.com/sagitarisandy',
      icon: '/img/icon/github.svg',
    },
    {
      id: 2,
      name: 'Linkedin',
      link: 'https://www.linkedin.com/in/arya-fadhil-sagitarisandy-b140831a8/',
      icon: '/img/icon/linkedin.svg',
    },
    {
      id: 3,
      name: 'Instagram',
      link: 'https://www.instagram.com/sagitarisandy/',
      icon: '/img/icon/instagram.svg',
    },
    // {
    //   id: 4,
    //   name: 'Facebook',
    //   link: 'https://www.facebook.com/ryandinulfatah',
    //   icon: '/img/icon/facebook.svg',
    // },
    {
      id: 4,
      name: 'Medium',
      link: 'https://medium.com/@sagitarisandybusiness',
      icon: '/img/icon/book-open.svg',
    },
    {
      id: 5,
      name: 'Email',
      link: 'mailto:sagitarisandybusiness@gmail.com',
      icon: '/img/icon/mail.svg',
    },
  ],
  techStack: [
    {
      id: 1,
      name: 'illustrator',
      type: 'database',
      icon: '/img/icon/adobe-illustrator.svg',
      year: '5 years',
    },
    {
      id: 2,
      name: 'Photoshop',
      type: 'programming',
      icon: '/img/icon/Adobe-Photoshop.svg',
      year: '6 year',
    },
    {
      id: 3,
      name: 'Adobe After Effects',
      type: 'programming',
      icon: '/img/icon/Adobe-After.svg',
      year: '1 year',
    },
    {
      id: 4,
      name: 'Figma',
      type: 'programming',
      icon: '/img/icon/Figma-logo.svg',
      year: '4 year',
    },
    {
      id: 5,
      name: 'Procreate',
      type: 'containerized',
      icon: '/img/icon/Procreate.svg',
      year: '4 year',
    },
    {
      id: 6,
      name: 'Maze',
      type: 'containerized',
      icon: '/img/icon/maze.jpeg',
      year: '5 month',
    },
    {
      id: 7,
      name: 'React Native',
      type: 'containerized',
      icon: '/img/icon/react.svg',
      year: '6 month',
    },
    {
      id: 8,
      name: 'React',
      type: 'containerized',
      icon: '/img/icon/react.svg',
      year: '1 year',
    },
    {
      id: 9,
      name: 'Flutter',
      type: 'containerized',
      icon: '/img/icon/flutter.svg',
      year: '2 month',
    },
    {
      id: 10,
      name: 'Dart',
      type: 'containerized',
      icon: '/img/icon/dart.png',
      year: '3 month',
    },
    {
      id: 11,
      name: 'Javascript',
      type: 'containerized',
      icon: '/img/icon/javascript.svg',
      year: '2 year',
    },
    {
      id: 12,
      name: 'CSS',
      type: 'containerized',
      icon: '/img/icon/css3.svg',
      year: '2 year',
    },
    {
      id: 13,
      name: 'HTML',
      type: 'containerized',
      icon: '/img/icon/html5.svg',
      year: '2 year',
    }
  ],
  testimonials: [
    
    {
      id: 1,
      name: 'Camping Store Panama',
      desc: 'It was wonderful working with Arya. He was very patient, talented, and very responsive. He quickly got the idea of what we needed. He chose a colour palette that goes perfect with our branding. The artwork turned out more awesome than  expected!  Im sure I will work with Arya again.',
      profile: '/img/certificate/camping-store.jpg',
      country: '🇵🇦 Panama',
    },
    {
      id: 2,
      name: 'Soluty Renting',
      desc: 'Really great work! The communication was easy, he totally understood our needs and gave us a excellent work. Hope we collaborate further',
      profile: '/Logo/soluty-renting-logo.png',
      country: '🇪🇸 Spain',
    },
    {
      id: 3,
      name: 'Dianna',
      desc: 'Sagitarisandy was excellent in asking questions upfront about the direction and the motivation behind my ask. I got a sketch to confirm the outline and updates throughout. He was prompt, took my feedback well and executed it, and delivered an excellent piece! I know where to go in the future for awesome digital illustrations!',
      profile: '/img/certificate/kristen-stewart.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 4,
      name: 'Tdao',
      desc: 'Its always a pleasure working w Arya. He understood our requirements and delivered exactly our vision. He even fix his previous designs for us so they can match with the new ones.',
      profile: '/img/certificate/tdao.webp',
      country: '🇻🇳 Vietnam',
    },
    // {
    //   id: 5,
    //   name: 'Mike',
    //   desc: 'Always a pleasure working Arya! Love his work.',
    //   profile: '/img/certificate/mike.webp',
    //   country: '🇺🇸 United States',
    // },
    {
      id: 6,
      name: 'Ejfran',
      desc: 'It was fantastic sagitarisandy made sure that my request fit my needs. We look over where the image would be used and he was able to work out my ideas and produced the best image for the project. sagitarisandy is very creative and responsive to input.',
      profile: '/img/certificate/mike.webp',
      country: '🇺🇸 United States',
    },
    // {
    //   id: 7,
    //   name: 'Notion Gems',
    //   desc: 'I aimed to present a polished image on my Twitter profile, and his illustration work was just what I needed. The avatar and cover were superb in quality, and I am delighted with the outcome. Strongly recommend.',
    //   profile: '/img/certificate/mike.webp',
    //   country: '🇮🇹 Italy',
    // },
    {
      id: 8,
      name: 'Joanna',
      desc: 'Super travail comme dhabitude ! Bravo Arya et merci !',
      profile: '/img/certificate/joanna.jpg',
      country: '🇫🇷 France',
    },
    {
      id: 9,
      name: 'Hasan',
      desc: 'Great work! Arya is a very talented illustrator and I’ll definitely hire for my future projects. Highly recommend',
      profile: '/img/certificate/hasan.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 10,
      name: 'Himanshu Batra',
      desc: 'Hes gold on this field. You shouldnt look further if youre looking for an illustration or website design. I had fun working with him on our website. He has built a full website confidently, and small changes went smoothly, and he had no issue with tiny changes or re-work. If youre looking for UI design, Figma Web Sites & Illustration for your website, he should be your go-to guy. Dont look any further. I highly recommend him for any web design-related projects. Must use.',
      profile: '/img/certificate/asharib-naseer.webp',
      country: '🇺🇸 United States',
    },
    {
      id: 11,
      name: 'Jacob',
      desc: 'His work is amazing and beyond my expectations. I would recommend him to everyone. He did many revisions with speed and no complaints. Hes the man! He also gave my advice on the design of my website, which is excellent.',
      profile: '/img/certificate/jacob.webp',
      country: '🇳🇿 New Zealand',
    },
  ],
  link: [
    {
      id: 1,
      text: 'View My Resume',
      url: 'https://drive.google.com/file/d/1_6LoLRxurPZxoqK9fQKOgVeKbAaULUAK/view?usp=drive_link',
    },
    {
      id: 2,
      text: 'Project Portofolio | download to preview',
      url: 'https://drive.google.com/file/d/1GKU1E2el9ctfq71_jtArMr_A09bsRlt2/view?usp=drive_link',
    },
    {
      id: 3,
      text: 'My Dribbble',
      url: 'https://dribbble.com/sagitarisandy/shots',
    },
    {
      id: 4,
      text: 'My Instagram',
      url: 'https://www.instagram.com/sagitarisandy/',
    },
    {
      id: 5,
      text: 'Send me an email',
      url: 'mailto:sagitarisandybusiness@gmail.com',
    },
    {
      id: 6,
      text: 'My Linkedin',
      url: 'https://www.linkedin.com/in/arya-fadhil-sagitarisandy-b140831a8/',
    },
    {
      id: 7,
      text: 'My Github',
      url: 'https://github.com/sagitarisandy',
    }
  ],
  sertifikasi: [
    {
      id: 1,
      title: 'Job : Frontend-Development Admin Design',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-2.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 2,
      title: 'Job : Need Laravel & MySQL for Develop App',
      platform: 'Upwork Client Feedback',
      img: '/img/certificate/new-testi-1.png',
      url: 'https://www.upwork.com/freelancers/~015effbba758bbdfe0',
    },
    {
      id: 3,
      title: 'Belajar Dasar Pemrograman Web',
      platform: 'Dicoding',
      img: '/img/certificate/new-dasar-web.png',
      url: 'https://www.dicoding.com/certificates/L4PQ3E06VPO1',
    },
    {
      id: 4,
      title: 'Belajar Fundamental Front-end Web Development',
      platform: 'Dicoding',
      img: '/img/certificate/new-frontend-fundamental.png',
      url: 'https://www.dicoding.com/certificates/MEPJLQ1KWZ3V',
    },
    {
      id: 5,
      title: 'Belajar Prinsip Pemrograman SOLID',
      platform: 'Dicoding',
      img: '/img/certificate/new-solid.png',
      url: 'https://www.dicoding.com/certificates/72ZDE5L99PYW',
    },
    {
      id: 6,
      title: 'Cloud Practitioner Essentials (Belajar Dasar AWS Cloud)',
      platform: 'Dicoding',
      img: '/img/certificate/new-aws-dasar.png',
      url: 'https://www.dicoding.com/certificates/ERZR4E6MQZYV',
    },
    {
      id: 7,
      title: 'Basic English Online Course for Programmer',
      platform: 'YEC.CO.ID',
      img: '/img/certificate/new-eng.png',
      url: '#',
    },
    {
      id: 8,
      title: 'Baparekraf Developer Day 2020',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-dev-day-2020.png',
      url: '#',
    },
    {
      id: 9,
      title: 'IDCAMP Virtual Graduation 2019',
      platform: 'Dicoding Event',
      img: '/img/certificate/new-virtual-graduation-2019.png',
      url: '#',
    },
    {
      id: 10,
      title: 'Course Studi Kasus Web Geolocation Laravel & Here Maps API',
      platform: 'Codepolitan',
      img: '/img/certificate/new-codepol.png',
      url: '#',
    },
    {
      id: 11,
      title: 'The Fundamentals of Digital Marketing',
      platform: 'Google Digital Garage',
      img: '/img/certificate/new-google-digital-marketing.png',
      url: '#',
    },
  ],
}
export default userData
